### ISSUE TITLE
Deploying locally from one Ruby env to another breaks Bundler

### ISSUE THREAD

**Issue by chewi** [capistrano/capistrano#1475] opened 2015-08-04 12:18 UTC
We're deploying directly to the host that cap is running on using `server :local`. Both cap and the deployment target are using RVM but under different gemsets. When it tries to do anything with Bundler like `bundle install` or `bundle exec rake`, it blows up, in this case complaining that rake isn't available. I'm afraid I don't have the exact error to hand now but it basically boils down to the Bundler environment leaking from one side to the other. I believe this problem would occur under other kinds of differing environments where Bundler is involved on both sides.

I wasn't explicitly running cap using `bundle exec` but Bundler was kicking in anyway because of rubygems-bundler, which I think is put in place by RVM. I was initially able to work around it by putting `exclude: [cap]` in `.noexec.yaml` but you may have a need to run cap under Bundler. Indeed, we're planning on experimenting with the capistrano-git-submodule-strategy gem and we'll probably need a `:github` entry in the Gemfile to begin with.

I couldn't find a simple way to clean the Bundler environment for each invocation of `bundle` but I reasoned that Bundler shouldn't be needed after the various requires in the Capfile so I put this at the end of it and it did the trick.

```ruby
class Capistrano::Application
  def top_level
    if defined? Bundler
      Bundler.with_clean_env do
        super
      end
    else
      super
    end
  end
end
```

Perhaps you could add this to the `Capistrano::Application` class but you'd need to judge how many people are calling `require` outside of the top-level. I'd guess next to none.

**Comment by leehambley** [comment] 2015-08-04 12:48
Thanks for the report, but surely this belongs in https://github.com/capistrano/bundler ?

**Comment by chewi** [comment] 2015-08-04 12:58
Yes and no. When I tried to get a clean environment for just each invocation of `bundle`, I started making changes there but when that didn't work, I realised the change would be needed in Capistrano itself. It's also possible that someone may execute `bundle` manually without using the gem.

**Comment by leehambley** [comment] 2015-08-04 13:00
Indeed, honestly the `:local` thing has no place in Capistrano, but every time I remove it, along with an argument why someone opens a PR to bring it back, as you have seen it does not work well, and is not suitable for any serious use. I'm sorry you lost time to something like this. If you might, since you seem to need it, what exactly is the use-case for using something designed for remote, multi server synchronisation to "deploy" an app you already have locally on disk that is not solved by either Rake or Thor?

**Comment by chewi** [comment] 2015-08-04 13:26
Actually, apart from this one issue which I'm happy enough to continue working around, it works fine here. Perhaps the fact that we've already moved to a system backed by ACLs, where we can deploy as ourselves rather than the shared user running Rails, has made this work better than it might have otherwise.

We were deploying remotely but have just switched to `:local` because our new environment is very locked down and we only allow SSH access from one specific access machine. We could deploy from there but it made more sense to pull our Capistrano files onto the target, which already has Ruby installed and already has access to the git server. The initial setup is done by Chef so all we have to do is jump on there and basically run `bundle install; cap deploy`.

I didn't consider Rake or Thor because Capistrano, whether local or remote, does exactly what we need it to do out of the box. This is a Rails application so it handles the assets and migrations, but even for our non-Rails stuff, it intelligently deploys each release whilst dealing with RVM and Bundler. I don't want to give that up! It's true that we are not using the multi-server aspect of it, beyond having multiple stages, but that's only a small part of the larger package.

I'm not aware of the reasons why you want to remove `:local` but if I come across any issues, I'll do my best to fix them myself.

**Comment by leehambley** [comment] 2015-08-04 13:32
Thanks for the detailed write up, that's certainly pretty backwards, but I'm coming from a background of Make and Rake hammers, and then… well, everything starts to look like a nail :) 

I feel your pain with Chef/Cap, and especially when ACLs and SELinux are involved, I actually don't use either ACLs or SELinux on any of my Capistrano deployed projects, but I can imagine how painful that might end up being.

With that (semi valid) use-case in mind, I'll stop complaining that `:local` is obsolete, broken by design and just accept that some people need it some of the time.

**Comment by mattbrictson** [comment] 2016-01-20 02:27
I think this qualifies as enhancement request for SSHKit's `Local` backend.

I'm closing this issue so that we can move the discussion to SSHKit: https://github.com/capistrano/sshkit/issues/317

**Closed by mattbrictson** 2016-01-20 02:27 UTC
