### ISSUE TITLE
undefined local variable or method `tasks_without_stage_dependency' for #<Capistrano::Application

### ISSUE THREAD

**Issue by whoru7777777** [capistrano/capistrano#1551] opened 2016-01-04 21:41 UTC
Hello I have been stuck here for days, I would really appreciate help. I have been to many site uninstalled and re-installed etceteras. Here is my error log. I am using Rails 4.2.3, Ruby 2.1.7-p400, Capistrano Version: 3.4.0 (Rake Version: 10.4.2), and the latest rubber gem. It seems rubber installed without error and bundles work as well as general rake and rails sever.

$cap rubber:create_staging --trace
cap aborted!
NameError: undefined local variable or method `tasks_without_stage_dependency' for #Capistrano::Application:0x007ff5fccf3600

/usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/lib/capistrano/application.rb:57:in top_level_tasks' /usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:106:inblock in top_level'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:115:in run_with_threads' /usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:100:intop_level'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:78:in block in run' /usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:176:instandard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:75:in run' /usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:inrun'
/usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/bin/cap:3:in <top (required)>' /usr/local/rvm/gems/ruby-2.1.7/bin/cap:23:inload'
/usr/local/rvm/gems/ruby-2.1.7/bin/cap:23:in <main>' /usr/local/rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:ineval'
/usr/local/rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `

**Comment by leehambley** [comment] 2016-01-04 21:44
What is `rubber` ?

**Comment by leehambley** [comment] 2016-01-04 21:45
Looks like a Gem for Capistrano 2.x wiki apparently not updated since 2012. Probably you need to install an older version of Capistrano. (something from the 2.x branch) See https://rubygems.org/gems/capistrano/versions

**Comment by whoru7777777** [comment] 2016-01-04 22:03
Thank You for the Response, That is one of the few things I have not tried.

**Comment by whoru7777777** [comment] 2016-01-04 22:29
Thank you for the response, I was able to resolve this by adding this line to my Capfile.
rubber is a gem (library)  that links my server's together...Passenger, NGINX, and Postgresl.

add after the line in the <Capfile> file <require 'capistrano'> added line below.
require 'capistrano/setup'

issue fixed.

**Comment by whoru7777777** [comment] 2016-01-04 22:37
I added this line<require 'capistrano/setup' after the the line <require 'capistrano'> in the <Capfile> file 

I lost the explanation in the last post sorry for that.

**Comment by mattbrictson** [comment] 2016-01-05 04:36
Duplicate of #1552

**Closed by mattbrictson** 2016-01-05 04:36 UTC

**Comment by whoru7777777** [comment] 2016-01-05 17:21
I thank you

**Comment by fdwillis** [comment] 2024-01-01 20:23
I need help here
