### ISSUE TITLE
[Continue Discussion] About Translation to Chinese

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#1759] opened 2016-08-29 08:48 UTC
_From @1c7 on May 28, 2016 4:8_

https://github.com/capistrano/capistrano/issues/1690
here is continue discussion about topic in above link

I am busy on deploy a Rails app.
So when i got time i would come back and see what can we do to translate the website.
I don't know much about jekyll and github page.
maybe I can just fork & pull request or something to translate. I don't know.
anyway, when i got time i would come back.
:D

_Copied from original issue: capistrano/documentation#191_

**Comment by leehambley** [comment] 2016-08-29 08:48
_From @chinakr on May 29, 2016 4:56_

Documentation is ver important. if needed, I'll do my bit. Thanks.

**Comment by mattbrictson** [comment] 2016-08-31 00:06
Closed as duplicate of #1690

**Closed by mattbrictson** 2016-08-31 00:06 UTC
