### ISSUE TITLE
multiple servers with 3.4.0

### ISSUE THREAD

**Issue by jamesmk** [capistrano/capistrano#1407] opened 2015-03-25 21:41 UTC
I have an app that was deploying to multiple servers fine on `3.3.5`. The servers shared an IP but had separate ports, so I'd connect to them like this:

```ruby
server '123.4.5.67',
  user: fetch(:deploy_user),
  roles: %w(web app db),
  port: 123,
  ssh_options: {
    forward_agent: true
  }

server '123.4.5.67',
  user: fetch(:deploy_user),
  roles: %w(web app),
  port: 124,
  ssh_options: {
    forward_agent: true
  }

server '123.4.5.67',
  user: fetch(:deploy_user),
  roles: %w(web app),
  port: 125,
  ssh_options: {
    forward_agent: true
  }
```

After upgrading to `3.4.0` capistrano is only connecting to the last defined server. Do I need to update my configuration or is this a new bug?

thanks

**Comment by leehambley** [comment] 2015-03-25 21:50
This is already reported, that ports should be taken into account when defining servers. As a workaround, do the following.

Add a `.ssh/config` file *to your project* (format the same as the system ssh config file) and define your three servers give them aliases such as "1, 2, 3" and then refer to *those* in your Capfile.

**Comment by leehambley** [comment] 2015-03-25 21:50
https://github.com/capistrano/sshkit/blob/master/CHANGELOG.md#120

**Comment by bibendi** [comment] 2015-05-05 04:22
Why was it necessary make such backward incompatibility? Users that is REALLY used!

In our organization access to the servers is available only through the ports. And adjust for capistrano not who does not intend to. Now every developer has to keep at your local version of ssh/config.

You should discuss these things with the community before develop.

**Comment by leehambley** [comment] 2015-05-05 04:43
You can also check in a ./project/.ssh/config, see capistrano/sshkit/README
at the end of the file, documented there.

**Comment by sahin** [comment] 2015-05-21 02:02
+1

@bibendi I am not sure your approach is very right. You are guys are building the capistrano and people are flexible to use in different several ways.

we have the same problem, we have several servers with different under several domain names. We have around 23 different ruby/rails projects. We have a script to pull the servers info from cloud services with ports and create server hostname, port: X . Having hard coded /.ssh/config seems pretty old school to me. Now we had to create host file then cap deploy

It will be great to consider these are different.

server 'deployer@worker-mll.xxxx.net:52201', roles: ["app", "web"],
server 'deployer@worker-mll.xxx.net:52202', roles: ["app", "web"], 
server 'deployer@worker-mll.xxx.net:52203', roles: ["app", "web"],

**Comment by sahin** [comment] 2015-06-18 02:52
?

**Comment by mattbrictson** [comment] 2016-01-20 02:37
Closing as duplicate of #1400

**Closed by mattbrictson** 2016-01-20 02:37 UTC
