### ISSUE TITLE
Very slow per command performance

### ISSUE THREAD

**Issue by smtlaissezfaire** [capistrano/capistrano#1934] opened 2017-10-11 17:21 UTC
I've been experiencing very slow per command performance.  Here's an example from my log:

https://gist.github.com/smtlaissezfaire/400bd4b0e50373eb0270f3bc9b0f9f6b

I thought with cap 3 connections would be re-used?  Once a connection is open, it shouldn't take 2-3 seconds to run one command, correct?

Let me know if I'm doing something wrong or if this should be filed on ssh-kit.  Or is this normal and acceptable performance for cap 3?

**Comment by leehambley** [comment] 2017-10-11 17:23
Cap will reuse commands within reason, it's actually quite dependent on a number of things that are outside our control, could you grab a section of your `/var/log/auth` log whilst Capistrano runs and see if you have a lot of SSH sessions being opened and closed?

Thanks

**Comment by smtlaissezfaire** [comment] 2017-10-11 17:48
That would be on the target machine, correct?

**Comment by leehambley** [comment] 2017-10-11 19:25
Right, so we can see if connection are being reused or not

**Comment by smtlaissezfaire** [comment] 2017-10-11 20:18
So turns out they are re-used.  So that's not it. 

https://gist.github.com/smtlaissezfaire/2304e658bc598a2803198500e24142d0

BTW, I had to look at `/var/log/secure` on one machine and `/var/log/auth.log` on another.

**Comment by mattbrictson** [comment] 2017-10-12 02:56
Perhaps the shell is taking a long time to load? Is there something in e.g. `~/.bashrc` that could take a long time?

**Comment by smtlaissezfaire** [comment] 2017-10-12 04:32
Ahhhhhhhhh...good call.  I put something around rvm in there.  I don't have time right now to check it out but that's probably my issue.  

I guess this also comes down to a mental model that breaks down for me. I'd assume .bashrc gets sourced only once, but you're saying it gets re-sourced with every new `execute` call?

**Comment by mattbrictson** [comment] 2017-10-12 05:29
> you're saying it gets re-sourced with every new execute call?

Yes, that is correct

**Comment by leehambley** [comment] 2017-10-12 05:40
To give you a bit of a mental model @smtlaissezfaire the nesting is as such:

- SSH Connection
  - SSH Session (Channel)
    - Shell (Bash)

So depending on the model you can skip the SSH _Connection_ phase, but you still open up a session/channel (v. cheap). The model works this way because you can also start something like SCP, or FFTP on a connection which replaces the "channel" and precludes the need for starting a shell.

If you have expensive shell startup time due to rbenv you might consider moving the rbenv to only _login_ shells, and using the capistrano-rbenv plugin for Capistrano.

The following link explains the shell, and I'd thought it was pretty comprehensive, maybe it's worth documenting how reuse of connections, channels and shells all ties in together _somewhere_ in the docs.

- http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

**Comment by leehambley** [comment] 2017-10-12 05:42
Cribbed from the `Net::SSH` docs (which we use inside SSHKit):

```ruby
require 'net/ssh'

Net::SSH.start('host', 'user', :password => "password") do |ssh|
  # capture all stderr and stdout output from a remote process
  output = ssh.exec!("hostname")
  puts output # downside, you don't get all the exit statuses, and separated output/error

  # open a new channel and configure a minimal set of callbacks, then run
  # the event loop until the channel finishes (closes)
  channel = ssh.open_channel do |ch|
    ch.exec "/usr/local/bin/ruby /path/to/file.rb" do |ch, success|
      raise "could not execute command" unless success

      # "on_data" is called when the process writes something to stdout
      ch.on_data do |c, data|
        $stdout.print data
      end

      # "on_extended_data" is called when the process writes something to stderr
      ch.on_extended_data do |c, type, data|
        $stderr.print data
      end

      ch.on_close { puts "done!" }
    end
  end

  channel.wait

  # forward connections on local port 1234 to port 80 of www.capify.org
  ssh.forward.local(1234, "www.capify.org", 80)
  ssh.loop { true }
end
```

**Comment by smtlaissezfaire** [comment] 2017-10-12 06:14
Yeah, originally I had it just in .bash_login but if you are trying to run some ruby file that depends on the ruby hashbang, it won't work with the cap rbenv plugin.  I'll try to source rbenv first.

**Comment by will-in-wi** [comment] 2017-10-12 11:39
It sounds like this isn't a Capistrano bug, and the root cause seems to be identified. Closing.

**Closed by will-in-wi** 2017-10-12 11:39 UTC
