### ISSUE TITLE
Capture isn't capturing complete file

### ISSUE THREAD

**Issue by greinacker** [capistrano/capistrano#1430] opened 2015-05-12 16:16 UTC
This is on 2.15.5 - I understand this is no longer supported, but I'm hoping someone might be able to at least point me in the right direction.

Inside :update_asset_mtimes, there is this line:

```
manifest_content = capture("[ -e #{shared_path.shellescape}/#{shared_assets_prefix}/manifest* ] && cat #{shared_path.shellescape}/#{shared_assets_prefix}/manifest* || echo").strip
```

Lately, I'm finding that it's not capturing the entire manifest file, but rather the data in that file is only being partially read into manifest_content.  The actual manifest-xxxxx.json file is about 179K, and it's reading about 150K of it.  It also seems to be someone random - it will occasionally work, but usually not.

Oddly, there were no code changes between the last time this worked, and now.

Any pointers on what the issue might be?  I'd love to upgrade to 3.x, but can't quite yet, so I'd love to get this working again...

**Comment by greinacker** [comment] 2015-05-12 17:11
Just in case anyone else runs into this problem, the workaround I'm using for the moment is to transfer the file to the local disk, rather than using capture. Here's the complete workaround code:

```ruby
namespace :deploy do
  namespace :assets do

    desc <<-DESC
      [internal] Updates the mtimes for assets that are required by the current release.
      This task runs before assets:precompile.
    DESC
    task :update_asset_mtimes, :roles => lambda { assets_role }, :except => { :no_release => true } do
      # Fetch assets/manifest contents.
      # overridden here to transfer file and read it, instead of running capture. For some reason capture was sometimes
      # truncating the data, which meant this task would fail.

      # manifest_content = capture("[ -e #{shared_path.shellescape}/#{shared_assets_prefix}/manifest* ] && cat #{shared_path.shellescape}/#{shared_assets_prefix}/manifest* || echo").strip
      manifest_content = ""
      manifest_file_exists = ('true' ==  capture("if [ -e #{shared_path.shellescape}/#{shared_assets_prefix}/manifest* ]; then echo 'true'; fi").strip)
      if manifest_file_exists
        manifest_filename = capture("ls #{shared_path.shellescape}/#{shared_assets_prefix}/manifest*").strip
        get manifest_filename, "tmp/temp_manifest.txt"
        manifest_content = File.read("tmp/temp_manifest.txt").strip
        File.delete("tmp/temp_manifest.txt")
      end

      if manifest_content != ""
        current_assets = parse_manifest(manifest_content)
        logger.info "Updating mtimes for ~#{current_assets.count} assets..."
        put current_assets.map{|a| "#{shared_path}/#{shared_assets_prefix}/#{a}" }.join("\n"), "#{deploy_to}/TOUCH_ASSETS", :via => :scp
        run <<-CMD.compact
          cat #{deploy_to.shellescape}/TOUCH_ASSETS | while read asset; do
            touch -c -- "$asset";
          done &&
          rm -f -- #{deploy_to.shellescape}/TOUCH_ASSETS
        CMD
      end
    end
  end  
end
```

I'll be the first to admit this is super hacky, but it does indeed work...and if your deploy stops working, super hacky isn't so bad. :)

**Comment by leehambley** [comment] 2015-05-12 18:05
Closing the issue as it really belongs on the [mailing list](https://groups.google.com/forum/#!forum/capistrano), but essentially I think it boils down to the way SSH works, you have one (or more, actually) channels and they receive events, for some reason it would appear that Cap 2 is failing to get all the events in the right order (the order is not guaranteed, anyway), we made the same mistake in the output handling in cap3 (actually SSHKit) where sometimes failed commands would send `channel.on_request “exit-status”` meaning the program terminated, however there were still `on_data` events coming down the wire with the output of the command, which we missed, because we assumed the `channel.on_request “exit-status”` meant it had finished. (I think, it's a while ago now).

Regardless, that probably sounds like nonsense, you can see a fairly clean example here - http://net-ssh.github.io/ssh/v2/api/classes/Net/SSH/Connection/Channel.html I would *guess* that you're seeing because the file is relatively large, that `capture()` is not waiting for all the on_data events before returning, because it's likely returning when it sees `channel.on_request “exit-status”` although there's no reason that.

**Comment by greinacker** [comment] 2015-05-12 19:01
Thanks a ton for your help, Lee!  I was thinking it was most likely network protocol-related (since I sometimes get different sizes transferred), and what you've described is generally consistent with what I'm seeing.

I did take a look at the `capture()` function you pointed to while debugging this; what I found was I would get a number of `:out` stream messages (seemed like 8-10 or so IIRC), then the block would complete. Based on what you've suggested, I'm thinking there was another pending set of data that maybe isn't sent to the block.  I tried to go a little deeper, looking at `invoke_command`, then `run`, and so on, but things seemed to get more complex at that point, so I started working on a workaround instead.

Given that v2 is pretty old, and I'm guessing none of this code is used in v3, and there is a reasonable workaround (above), I'm think I'm inclined to just drop it for now...if you agree, feel free to close this issue if you'd like!

**Comment by leehambley** [comment] 2015-05-12 20:03
Yeah, actually the issue is really strange, and as I said, we made (well, I made) the same mistake in SSHKit which backs v3. The 2x code is really, really poorly tested, and prone to failure, I'd suggest an up grade when you can. Ping me if I can help with that.

**Closed** 2015-05-12 20:03 UTC
