### ISSUE TITLE
Can't use custom stage variables in deploy.rb

### ISSUE THREAD

**Issue by pablocrivella** [capistrano/capistrano#1413] opened 2015-03-30 16:03 UTC
```ruby
# config/deploy/sandbox.rb
set :branch, 'develop'
set :stage, :sandbox
set :user, 'vagrant'

server 'smrt-ruby-devbox.local', roles: %w(app web), user: fetch(:user)

set :rails_env, 'development'
```

```ruby
# config/deploy.rb
# config valid only for current version of Capistrano
lock '3.4.0'

set :application, 'app'
set :repo_url, 'git@github.com:company/app.git'
set :deploy_user, -> { fetch(:user, 'deploy') }
set :deploy_to, "/home/#{fetch(:deploy_user)}/apps/#{fetch(:application)}-#{fetch(:stage)}/"
```

I don't know why but ```deploy_user``` is always ```deploy```, but with the ```stage``` variable works ok.
Also ```rails_env``` doesn't work.

**Comment by leehambley** [comment] 2015-03-30 18:15
The problem is that in `deploy.rb` you use `:deploy_user` which resolves, and subsequently caches the value currently set.

I would suggest the following:

``` ruby
set :deploy_user, -> { fetch(:user, 'deploy') }
set :deploy_to,  -> { "/home/#{fetch(:deploy_user)}/apps/#{fetch(:application)}-#{fetch(:stage)}/" }
```

To defer resolving both until `deploy_to` is first used

**Closed by leehambley** 2015-03-30 18:15 UTC

**Comment by pablocrivella** [comment] 2015-03-30 21:13
great, thanks @leehambley

**Comment by adiakritos** [comment] 2015-04-01 20:00
What about the rails_env issue. I'm trying to figure that one out right now, unless lee's answer address that as well and I'm missing it.

**Comment by pablocrivella** [comment] 2015-04-01 20:19
Hey @adiakritos, the rails_env was also related to that.

This is my deploy.rb file: 

```ruby
# config valid only for current version of Capistrano
lock '3.4.0'

set :application, 'smrt-api'
set :repo_url, 'git@github.com:nobelbiz/smrt-api.git'
set :deploy_to, -> { "/home/#{fetch(:deploy_user)}/apps/#{fetch(:application)}/" }
set :rbenv_type, :system
set :rbenv_ruby, File.read('.ruby-version').strip
set :linked_files, fetch(:linked_files, []).push('config/database.yml',  'config/secrets.yml', 'config/admin.yml')
set :linked_dirs,  fetch(:linked_dirs,  []).push('bin', 'log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/bundle', 'public/system')
set :forward_agent, true
set :puma_rackup, -> { File.join(current_path, 'config.ru') }
set :puma_state, -> { "#{shared_path}/tmp/pids/puma.state" }
set :puma_pid, -> { "#{shared_path}/tmp/pids/puma.pid" }
set :puma_bind, -> { "unix://#{shared_path}/tmp/sockets/puma.sock" }
set :puma_conf, -> { "#{shared_path}/puma.rb" }
set :puma_access_log, -> { "#{shared_path}/log/puma_access.log" }
set :puma_error_log, -> { "#{shared_path}/log/puma_error.log" }
set :puma_env, -> { fetch(:rack_env, fetch(:rails_env, 'production')) }
set :puma_role, :app
set :puma_threads, [0, 16]
set :puma_workers, 2
set :puma_worker_timeout, nil
set :puma_init_active_record, true
set :puma_preload_app, true
```

I was having issues because the puma variables wasn't using lambdas. Maybe your problem is similar, you could be missing a var that needs to be lazy loaded.
