### ISSUE TITLE
Missing rollback documentation

### ISSUE THREAD

**Issue by streetlogics** [capistrano/capistrano#1556] opened 2016-01-08 18:24 UTC
http://capistranorb.com/documentation/getting-started/rollbacks/#

<img width="1280" alt="00000080" src="https://cloud.githubusercontent.com/assets/249509/12205762/efd68856-b5f9-11e5-8285-eadda94a10dd.png">

Is this for real?  I've used capistrano for years, specifically because I tell people "rollbacks are seamless", and then today, when the dreaded scenario of the deploy going bad actually happened, deploy:rollback failed me big time.  It appeared to work, but the code definitely wasn't rolled back, and then add to that the fact that every single solution on the internet was incompatible with Capistrano 3, I was left standing with a giant bag of rocks and a documentation page that makes it look like I chose an amateur hour gem to handle my code's production level deployments.  Thanks a lot guys.

**Comment by mattbrictson** [comment] 2016-01-08 18:41
Closing this as a duplicate of https://github.com/capistrano/documentation/issues/124.

> It appeared to work, but the code definitely wasn't rolled back

This sounds like a bug. If you have more details on this, please open a separate issue so that we have a place to start troubleshooting. Thanks.

**Closed by mattbrictson** 2016-01-08 18:41 UTC
