### ISSUE TITLE
Add Git submodule support

### ISSUE THREAD

**Issue by paulschreiber** [capistrano/capistrano#1409] opened 2015-03-30 02:12 UTC
Please add official submodule support. I spent a few hours this afternoon trying various submodule solutions found around the web.

Some of them do weird things, like `find .git` and `rm` or `rsync`. None of them seem to properly cache the submodule, which means it's getting cloned on every deploy, which is super inefficient.

**Comment by dwradcliffe** [comment] 2015-08-12 12:52
+1

**Comment by leehambley** [comment] 2015-08-12 13:19
This is largely blocked by https://github.com/capistrano/capistrano/issues/929 which would then allow us to have a `git` (naïve) and a git with submodule (or, one with some options) plugins. As it is, there's already a bit too much special-casing in the core.

**Comment by tymat** [comment] 2015-11-13 14:27
This needs to be added.  +1

**Comment by mani95lisa** [comment] 2015-12-02 13:19
+1

**Comment by 1st8** [comment] 2016-12-21 14:27
I proposed a way to handle `:git_enable_submodules` in https://github.com/capistrano/capistrano/pull/1823 which works nicely for me so far.
Please let me know what you think.

**Comment by aiyanbo** [comment] 2017-01-12 07:37
+1

**Comment by 1st8** [comment] 2017-01-12 08:24
Could you try https://github.com/ekho/capistrano-git-with-submodules ?
It works great for me.

**Comment by leehambley** [comment] 2017-01-12 09:06
Ekho's plugin is the way this was intended to be solved. The SCM plugin code that landed ~3.6-3.7 was intended to support just this use-case. Git submodules are not without their downsides and complexities, so we took care to make them pluggable so that people could pick their preferred method.

**Closed by leehambley** 2017-01-12 09:06 UTC
Labels: new feature
