### ISSUE TITLE
Using different gemsets with rvm for local tasks

### ISSUE THREAD

**Issue by MichaelMallett** [capistrano/capistrano#1359] opened 2015-02-04 20:41 UTC
I have come across a couple of sort of efforts to document this, and another that is out of date: I want to run compass compile through the projects already defined rvm gemset, using capistrano, and then upload the compiled css to the production server, which was installed using a different gemset. I would assume that capistrano wouldn't force you to fix to a ruby version and gemset as these are all different across projects, would it?

Anyway, I am trying to get capistrano working with a drupal site, specifically with the gemsets that the project was set up with long ago. 

So, we have a themes folder where we run rvm 1.9.3@omega do compass compile, and capistrano installed to 2.1.5@deploy a few folders above it.

I am running this task:

desc "Compile locally"
  task :compile_locally do
    run_locally do
      execute "cd ../#{fetch(:theme_path)} && rvm 1.9.3@omega do compass compile"
    end
  end

Which outputs this command
cd ../docroot/sites/all/themes/omega && rvm 1.9.3@omega do compass compile

Which works fine from the command line, in the folder I run cap from...however I get this error message when I try and run cap production deploy

cap aborted!
SSHKit::Command::Failed: cd ../docroot/sites/all/themes/omega && rvm 1.9.3@omega do compass compile exit status: 256
cd ../docroot/sites/all/themes/omega && rvm 1.9.3@omega do compass compile stdout: Nothing written
cd ../docroot/sites/all/themes/omega && rvm 1.9.3@omega do compass compile stderr: /Users/MIchael/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': compass is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

Which suggests it is not using the right ruby gem...which I can kind of understand as capistrano is using that version of ruby...however I'm a bit stuck how to get round it. I don't want to have to manually compile compass everytime.

I should point out that I am very much learning capistrano, and ruby in general, so I am happy to take on board any ideas about how to go about this properly

**Comment by leehambley** [comment] 2015-02-04 21:33
You might better ask in `capistrano/rvm` or the mailing list, those plugins for specific ecosystems are independently maintained, and authors aren't necessarily in the loop about this issue you've opened.

**Comment by leehambley** [comment] 2015-02-04 21:53
Also, since you're not benefitting from any of the Capistrano stuff here (by composing your one liner, `cd` and execute-this-thing line all yourself - try reading and experimenting with the following:

http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

Also, the problem is bundler, "thingy is not part of the Gemfile" is simply because something on your machine is effectively turning what you typed into "bundle exec compass"… which won't work in a directory where there's a Gemfile, and compass is not part of it.

Closing this issue, after reading it a couple more times, it's certainly not a Capistrano issue, possibly something with bundler or rvm, but again almost certain;y not with our integrations with them, but check with the maintainers of `capistrano/bundler` and `capistrano/rvm`

**Closed by leehambley** 2015-02-04 21:53 UTC

**Comment by MichaelMallett** [comment] 2015-02-04 22:54
Ok, thanks for the information
