### ISSUE TITLE
Deployment bug when you change remote repository

### ISSUE THREAD

**Issue by d4ins** [capistrano/capistrano#1812] opened 2016-12-06 22:01 UTC
Dear Capistrano team,

Recently I changed my repository from _bitbucket_ to _gitlab_ and face problem with deploy. My deployment, even if it was changed in `deploy.rb`, still wanted to connect to _bitbucket_.

Yes, I figure it out. I had to go to my server, and change `repo/config` file manualy. Basically, it's not a big deal and if you know what to correct and why problem appears it's easy to fix.

But still, as a suggestion. I think it would be more user friendly to correct this behavior to more logical => if you change repo in `deploy.rb` - then it's connection to changed repo, not to the old one.

**Comment by mattbrictson** [comment] 2016-12-06 22:10
Thanks for the report; it is a good suggestion. We are already tracking this in #1545. If you have the capacity to help fix this, we would appreciate the contribution!

Closing as duplicate of #1545.

**Closed by mattbrictson** 2016-12-06 22:10 UTC
