### ISSUE TITLE
Capitrano asks for password twice with sshkit version 1.11.0 and up

### ISSUE THREAD

**Issue by RogerE** [capistrano/capistrano#1774] opened 2016-09-06 11:38 UTC
After upgrading Capistrano, and consequently sshkit, to the latest version I am prompted for the password twice for tasks connecting to the server. Specifically, it prompts for the password on the first command(as normal), runs that command and then prompts for the password again on the second command. After that everything works as normal.

After some experimenting I found that this happens with version 1.11.0 and above of sshkit. Downgrading sshkit to 1.10.0 solves the issue.

Environment

```
Ruby     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Rubygems 2.6.4
Bundler  1.12.5
Command  /usr/local/lib/ruby/gems/2.3.0/bin/cap production doctor
```

Gems

```
capistrano          3.6.1
airbrussh           1.1.0
rake                11.2.2
sshkit              1.11.2
net-ssh             3.2.0
capistrano-bundler  1.1.4
capistrano-git-copy 1.2.0
capistrano-harrow   0.5.3
capistrano-rails    1.1.7
```

**Comment by will-in-wi** [comment] 2016-09-06 12:41
Could you add `--trace` to the Capistrano command and attach the output, indicating the points at which the password is being requested?

Thanks!

**Comment by RogerE** [comment] 2016-09-06 13:17
Example trace with password prompts included. Username and IP have been changed:

bundle exec cap --trace production deploy:check
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env 
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git_copy:check (first_time)
** Invoke git_copy:wrapper (first_time)
** Execute git_copy:wrapper
** Execute git_copy:check
00:00 git_copy:check
      01 git ls-remote --heads .
      01 822a55ecd9c3b20449f4c285f04704e322c8e685	refs/heads/master
    ✔ 01 vagrant@localhost 0.021s
** Invoke deploy:check:directories (first_time)
** Execute deploy:check:directories
00:00 deploy:check:directories
      01 mkdir -p /home/user/apps/forsidene/shared /home/user/apps/forsidene/releases
@1.2.3.4's password: 
    ✔ 01 user@1.2.3.4 8.839s
** Invoke deploy:check:linked_dirs (first_time)
** Execute deploy:check:linked_dirs
00:08 deploy:check:linked_dirs
      01 mkdir -p /home/user/apps/forsidene/shared/log /home/user/apps/forsidene/shared/public/system /home/user/apps/forsidene/shared/tmp/cache /h…
user@1.2.3.4's password: 
    ✔ 01 user@1.2.3.4 6.720s
** Invoke deploy:check:make_linked_dirs (first_time)
** Execute deploy:check:make_linked_dirs
** Invoke deploy:check:linked_files (first_time)
** Execute deploy:check:linked_files

**Comment by mattbrictson** [comment] 2016-09-06 22:49
Thanks for detailed the report! I think I've seen this as well.

It's not obvious to me what could cause this. Probably what we'll need to do is run a `git bisect` on SSHKit and see what commit introduced the bug. As you said, it is something between 1.10.0 and 1.11.0, right?

I'll try to get to this later this week. If someone wants to jump on this in the meantime, feel free!

**Comment by mattbrictson** [comment] 2016-09-06 22:54
@RogerE I noticed the two password prompt are slightly different:

```
@1.2.3.4's password: 
user@1.2.3.4's password:
```

Was this a copy/paste error or were they actually different in the original log output?

**Comment by RogerE** [comment] 2016-09-07 06:00
@mattbrictson the promts are actually the same, must have happened when I anonymized username/IP. Sorry for the confusion.

To your previous question, yes, it happens with 1.11.0 but not with 1.10.0.

**Comment by leehambley** [comment] 2016-09-07 06:08
The [compare view](https://github.com/capistrano/sshkit/compare/v1.10.0...v1.11.0) doesn't show anything immediately obvious.

Are you skilled enough with Git @RogerE to perhaps run a [`git bisect`](https://git-scm.com/docs/git-bisect) for us over the 18 commits (ok, realistically it's ~15 actual code changes)  and give us a clue about where the breaking change was introduced?

I think the strategy to bisect would be:

```
$ cd code/
$ vim code/my_project/Gemfile # add `gem 'sshkit', path: '../sshkit'`
$ git clone https://github.com/capistrano/sshkit.git
$ cd sshkit
$ git bisect start --term-good=v1.11.0 --term-bad=v1.11.0
```

For each commit in the range bisect will basically do a binary search checking out each commit and asking you whether this is "good" or "bad", for some things (unit tests, for example) this can take a command to automatically run, if it exists `0`, the commit is good, otherwise bad, and Git can run the search automatically.

In our case however you'll need to run a `cap ....... deploy` in another console/terminal and tell git manually whether this was the result you expected, or not, it should narrow down the commit **very** quickly this way.

If you need a hand @RogerE (it's hard to know whether people have entered all dark corners of Git) drop me an email and I'll jump on a short call/skype/hangout/etc and we can step through it together.

**Comment by RogerE** [comment] 2016-09-07 06:32
Thanks @leehambley, here is the final output of git bisect:

27b88cab9d3978802890263a8e0e23d77ac2772e is the first bad commit
commit 27b88cab9d3978802890263a8e0e23d77ac2772e
Author: Jean Boussier <jean.boussier@gmail.com>
Date:   Fri Mar 11 14:23:23 2016 -0500

    Make cached known hosts lookup the default

**Comment by leehambley** [comment] 2016-09-07 07:17
thanks for going through the hassle of the `git bisect` @RogerE , to confirm then that before this commit you are prompted once, as expected, and after this commit you are prompted twice, which is to be considered a bug?

**Comment by leehambley** [comment] 2016-09-07 07:34
@RogerE here's from my IRB session, but you can adapt the code for your Capistrano recipe, unfortunately it doesn't work yet, but this is the vein I'm following:

```
$ irb -rsshkit
irb(main):005:0> cacheless_config = SSHKit::Backend::Netssh::Configuration.new.tap { |c| ssh_options = {known_hosts: nil} }
irb(main):011:0> SSHKit::Backend::Netssh.class_eval("@config = cacheless_config")
irb(main):013:0> SSHKit::Backend::Netssh.config.ssh_options
=> {:known_hosts=>#<SSHKit::Backend::Netssh::KnownHosts:0x007f85089e2818 @_mutex=#<Thread::Mutex:0x007f85089e2778>, @files={}>}
```

**FWIW this doesn't seem to work**, but it's been a while since I worked with Ruby and mangling class variables, and overriding defaults, etc.... 

By the way, why are you using *password authentication*, it's barely supported, and often a horrible idea, keys are much better in almost every case, so I *have* to ask!

**Comment by RogerE** [comment] 2016-09-07 09:02
@leehambley I must admit this is a bit above my current level of expertise...

But to be clear, this is not a big issue for me, I can avoid it for now by specifying sshkit 1.10.0, just thought it would be good to let you know about it.

And yes, I know I should use keys, I'll probably look into it the next time I set up a new server. But I sort of like the friction of having to enter a password, as reminder to check that I'm in the right project, doing the right thing etc. My understanding is I can require a passphrase for a key, but this  may generate the same issue?

**Comment by leehambley** [comment] 2016-09-07 10:15
> @leehambley I must admit this is a bit above my current level of expertise...

Makes two of us apparently, the APIs around host caching weren't meant to be easily over-rideable, thanks non the less for doing the Git bisect with us. Maybe @mattbrictson will know how we can jump the hoops of class variable defaults etc and make a fix in code. (I suspect we need to add an API to set the options after initialization)

> But to be clear, this is not a big problem for me, I can avoid it for now by specifying sshkit 1.10.0, just thought it would be good to let you know about it.

Absolutely, at least we know it's a confirmed bug now, it probably ought to be moved to https://github.com/capistrano/sshkit where the problem originates, but let's get some other opinions first.

> My understanding is I can require a passphrase for a key, but this may generate the same issue?

Yes and no, the key is loaded into a key agent on most operating systems, so the key is loaded once per "session", and you can set an agent timeout of say, 5 min, so that after 5 min the agent requires the passphrase to be entered again.

If you've no experience whatsoever with SSH keys, and agents it can be a steep (but, very worthwhile) learning curve, unfortunately in your naïve case, the server would probably *still* ask you for a password if you'd forgotten to load the key into the agent... fortunately it is trivial (and you can ask me any time for help) to add a guard to Capistrano that *requires* the agent to have some keys, or to disable password authentication entirely on the server, which is a smart move for security, but might carry a big risk of locking yourself our of your machines if you're not careful with keys/etc.

**Comment by RogerE** [comment] 2016-09-07 10:39
@leehambley interesting, I'll spend some time getting up to speed on SSH keys in the not to distant future.

For now, thank you very much for your swift and comprehensive responses!

**Comment by will-in-wi** [comment] 2016-09-07 12:14
@RogerE Another approach for SSH keys is to run:

```
ssh-agent bash # Or your shell
ssh-add ~/.ssh/id_rsa # Or whatever key you choose
bundle exec cap <stage> deploy
exit
```

The first command starts a new bash shell with SSH Agent running inside. The second command pulls in an SSH Key and, assuming you have it encrypted, prompts you for the password. The third command of course runs Capistrano, but now the key is available to it. The fourth command exits the newly created SSH Agent shell and closes the agent process.

The guide I use to create keys is here: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key You can skip the section on adding it to SSH Agent. Once you create a key, add the public key (`id_rsa.pub`) to the server in `~/.ssh/authorized_keys`. Make sure that `~/.ssh` is `chmod 700` and `~/.ssh/authorized_keys` is `chmod 600`, otherwise SSH will ignore them silently.

**Comment by mattbrictson** [comment] 2016-09-07 14:38
@RogerE Can you try adding this to your `deploy.rb` as a potential workaround?

```
set :ssh_options, known_hosts: Net::SSH::KnownHosts
```

**Comment by mattbrictson** [comment] 2016-09-07 17:46
I found the cause of the bug and opening a corresponding issue in SSHKit: https://github.com/capistrano/sshkit/issues/369

**Comment by leehambley** [comment] 2016-09-07 19:17
Thanks Matt, great detective work

(Sent from my Nexus 6, please forgive typos!)

**Comment by RogerE** [comment] 2016-09-08 06:00
@mattbrictson thanks, with your workaround added I am only promoted once with the newest version of sshkit. And I see you have found the cause of this also which is great! 

Let me know if there is anything else I can do to help.

**Comment by RogerE** [comment] 2016-09-08 06:01
Thanks @will-in-wi I'll look into it.

**Comment by mattbrictson** [comment] 2017-02-16 02:09
Closing in favor of https://github.com/capistrano/sshkit/issues/369

**Closed by mattbrictson** 2017-02-16 02:09 UTC
Labels: confirmed bug
