### ISSUE TITLE
update_asset_mtimes doesn't find manifest

### ISSUE THREAD

**Issue by vpuzzella** [capistrano/capistrano#1702] opened 2016-06-16 17:15 UTC
Version 2.15.8
#### Steps to reproduce
1. run cap deploy:assets:update_asset_mtimes
#### Expected behaviour

Should successfully find manifest file and capture content
#### Actual behaviour

Does not find manifest file. I believe the bash command is incorrect. The wildcard should be placed outside of the quoted file path, like so:

```
      manifest_content = capture("[ -e '#{shared_path.shellescape}/#{shared_assets_prefix}/#{asset_manifest_prefix}'* ] && cat #{shared_path.shellescape}/#{shared_assets_prefix}/#{asset_manifest_prefix}* || echo").strip
```

**Comment by mattbrictson** [comment] 2016-06-16 17:29
Thanks for the report! Generally speaking we no longer support Capistrano 2.x, so I suggest testing out your proposed fix with your own fork of the project.

We'll consider accepting a PR for 2.x if you can make a strong case that this is a critical bug.

**Comment by vpuzzella** [comment] 2016-06-16 17:32
Patch: https://github.com/capistrano/capistrano/pull/1703

**Comment by mattbrictson** [comment] 2016-06-16 17:45
> IMO, it's pretty critical because asset mtimes are not being touched. That causes deploy:assets:clean_expired to remove required assets.

So everyone using 2.x to deploy a Rails app is seeing all of their assets being deleted? If so I would think this would be widely reported. Is this a recent regression?

**Comment by vpuzzella** [comment] 2016-06-16 18:57
Hard to say. Might be platform related (centos in my case). Or, not many people use the deploy:assets:clean_expired task. In may case, I added `after "deploy:restart", "deploy:cleanup"` which triggers ```deploy:assets:clean_expired```.

**Comment by vpuzzella** [comment] 2016-06-16 19:00
Here is a simple test I ran on my centos box:
```
$ [ -e 'README*' ]; echo $?
1
$ [ -e 'README'* ]; echo $?
0
```

**Comment by mattbrictson** [comment] 2016-06-16 19:08
OK, thanks for taking the time to explain. Can you do some more digging as to why the code was written the way it was? For example, it seems that your change will undo the fix for https://github.com/capistrano/capistrano/issues/578 (see also commit https://github.com/vpuzzella/capistrano/commit/57633b211f4fa260c2a85e98c2558497c4ac4fb4).

Please understand that I have no way of testing v2, so I have to be very careful about accepting PRs that have even a slight chance of introducing bugs or regressions.

**Comment by vpuzzella** [comment] 2016-06-16 19:24
The fix in #578 adds quotation marks and keeps the wildcard within the quotes. I'm proposing moving the  wildcard outside of the quotes which doesn't exactly 'undo' the original fix.That said, I still think this may be platform related and I understand the reluctance. I'm happy to use my own fork until I have a chance to upgrade.

**Comment by vpuzzella** [comment] 2016-06-16 19:25
Some reference: http://stackoverflow.com/questions/6363441/check-if-a-file-exists-with-wildcard-in-shell-script

**Comment by mattbrictson** [comment] 2016-06-17 16:27
OK, given the risks let's just leave this open for now.

**Comment by SakthiGurunathan07** [comment] 2016-12-20 06:04
@vpuzzella @mattbrictson  whether this issue will be fixed ?? Is there any way to override capistrano internal task update_asset_mtimes

**Comment by leehambley** [comment] 2016-12-20 14:18
- http://blog.jayfields.com/2008/02/rake-task-overwriting.html

Capistrano tasks are rake tasks, so this 2008 guide works fine.

**Comment by mattbrictson** [comment] 2016-12-20 16:34
@SakthiGurunathan07 to be honest, it is unlikely that this issue will be fixed. It is a Capistrano v2 issue, which is an old version we no longer support.

**Comment by leehambley** [comment] 2016-12-20 18:13
Closing the issue, I consider that since 3.x is more than three years old now, 2.x is EOL and won't recieve any more updates.

**Closed** 2016-12-20 19:46 UTC
Labels: bug?, v2
