### ISSUE TITLE
How to avoid parallel deployment?

### ISSUE THREAD

**Issue by zocoi** [capistrano/capistrano#1529] opened 2015-11-25 22:12 UTC
Hi

I'm using capistrano 3.4.0 to deploy to several hosts under a load balancer. I need to deploy each of the hosts one by one with the following: taking it out of rotation, deploy, smoke tests and put it back to rotation. Is there any way I can achieve that with capistrano config?

The best I can think of is overridng deploy task using HOST filter.

My current config always deploy all hosts in parallel which is not optimal in our case. Any hint or plugin is appreciated.

**Comment by leehambley** [comment] 2015-11-25 22:21
The problem is more likely the *restart* than the deployment, right? What are you using for restarts? A plugin or a borne out example from the generated files?

**Comment by zocoi** [comment] 2015-11-30 19:27
@leehambley I'm using puma server and `capistrano3-puma` gem which provides some tasks to start, stop and restart the server. One problem with `restart` is that Capistrano 3 doesn't roll back anymore, so if one host has a failed smoke test, the rest of the hosts won't be restarted. However, all the host will have the latest code and it makes the manual restart ugly.

Any thoughts on this?

**Comment by leehambley** [comment] 2015-11-30 20:16
> @leehambley I'm using puma server and capistrano3-puma gem which provides some tasks to start, stop and restart the server.

Ping the puma plugin author about implementing rolling restarts, it should be trivial, or open up the gem and rip the part of it you need out, replacing the standard `on()` with one passing options to make a rolling restart.

> One problem with restart is that Capistrano 3 doesn't roll back anymore, so if one host has a failed smoke test, the rest of the hosts won't be restarted.

I don't understand the problem there, strictly you should make sure that you run Cap (it's not a responsibility we can solve properly) in a way that if it exists with a non-zero status, you then restart.

> However, all the host will have the latest code and it makes the manual restart ugly.

You should "rollback" by redeploying the last known good version. The "rollback" is really, really unlikely to work in any but the simplest of scenarios, when framed this way a "rollback" is just a new deploy, and theoretically your app comes back into a known-good state.

**Comment by mattbrictson** [comment] 2016-01-20 02:08
Capistrano was built to run an identical set commands across a group of servers. To run the entire deploy flow against one server, smoke test, then move onto the next is unfortunately not within the realm of what Capistrano can do alone.

I think you need to write a script or use some other orchestration tool to manage your rollout process, and have that tool wrap Capistrano.

I'm closing this issue because I don't think there is anything we can reasonably change in Capistrano to address this scenario. If you have any ideas, please let us know and we can reopen to continue the discussion.

**Closed by mattbrictson** 2016-01-20 02:08 UTC
